#! /bin/bash

#   Add service file to runlevel directory

/bin/cp /etc/init.d/fprintd-openrc /etc/runlevels/default || true

#   Add service to runlevel

rc-update add fprintd-openrc default

#   Update services list

rc-update -u
